---
engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    checks:
      import/no-duplicates:
        enabled: false
      no-template-curly-in-string:
        enabled: false
      import/no-unresolved:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
      import/no-named-as-default-member:
        enabled: false
ratings:
  paths:
  - "**.js"
exclude_paths:
  - coverage/**/*
  - es/**/*
  - lib/**/*
  - node_modules/**/*
  - test/**/*
