---
version: '2'
checks:
  method-complexity:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - coverage/**/*
  - esm/**/*
  - demo/**/*
  - lib/**/*
  - node_modules/**/*
  - test/**/*
